from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

SQL_OUTPUT_PATH = REPO_ROOT / "retail_ops" / "outputs" / "store_a_demo1_sql_output.csv"
INTERPRETATION_SUMMARY_PATH = (
    REPO_ROOT / "retail_ops" / "outputs" / "store_a_demo1_interpretation_summary.csv"
)
GENERATED_FACTS_PATH = (
    REPO_ROOT / "retail_ops" / "outputs" / "generated_retail_memory_facts.json"
)
RETAIL_VALIDATION_RESULT_PATH = (
    REPO_ROOT / "retail_ops" / "outputs" / "retail_data_contract_validation_result.txt"
)


def run_command(command: list[str], *, capture_to: Path | None = None) -> None:
    print(f"\n$ {' '.join(command)}")

    result = subprocess.run(
        command,
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
    )

    if result.stdout:
        print(result.stdout, end="")

    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)

    if capture_to is not None:
        capture_to.parent.mkdir(parents=True, exist_ok=True)
        capture_to.write_text(result.stdout, encoding="utf-8")

    if result.returncode != 0:
        raise SystemExit(result.returncode)


def require_file(path: Path, description: str) -> None:
    if not path.exists():
        raise SystemExit(f"Missing required {description}: {path.relative_to(REPO_ROOT)}")
    print(f"Checked existing {description}: {path.relative_to(REPO_ROOT)}")


def main() -> int:
    print("Regenerating Demo 1 SQL diagnostic output and validating retail consistency.")
    print(
        "Note: this script regenerates the SQL diagnostic output only. "
        "The interpretation summary and generated memory facts are checked for consistency "
        "by validators, but are not regenerated by this script."
    )

    run_command([sys.executable, "retail_ops/scripts/export_demo1_sql_output.py"])

    require_file(SQL_OUTPUT_PATH, "SQL diagnostic output")
    require_file(INTERPRETATION_SUMMARY_PATH, "interpretation summary")
    require_file(GENERATED_FACTS_PATH, "generated retail memory facts")

    run_command(
        [sys.executable, "retail_ops/scripts/validate_retail_data_contract.py"],
        capture_to=RETAIL_VALIDATION_RESULT_PATH,
    )

    run_command([sys.executable, "scripts/validate_project_consistency.py"])

    print("\nDemo 1 SQL output regeneration and validation completed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
